spring:
  datasource:
    url: jdbc:mysql://localhost/vollmed_api
    username: sidney
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        page-parameter: pagina
        size-parameter: tamanho
      sort:
        sort-parameter: ordem
